spring:
  application:
    name: weather-tracker-service
  datasource:
    url: jdbc:postgresql://localhost:5432/haricharan
    username: haricharan
    password: haricharan
  jpa:
    hibernate:
      ddl-auto: update